CREATE TABLE PERSON
(
NID VARCHAR2(15),
NAME VARCHAR2(50) NOT NULL UNIQUE,
BDATE DATE DEFAULT SYSDATE,
CONSTRAINT PERSON_PK PRIMARY KEY (NID)
) ;
DROP TABLE PERSON;
CREATE TABLE PERSON
(
PERSON_ID NUMBER,
FIRST_NAME VARCHAR2(50) NOT NULL,
LAST_NAME VARCHAR2(50) NOT NULL,
GENDER VARCHAR2(10) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
PASSWORD VARCHAR2(50) NOT NULL,
PHONE NUMBER NOT NULL,
BIRTH_DATE DATE,
REGISTRATION_DATE DATE NOT NULL,
CONSTRAINT PERSON_PK PRIMARY KEY (PERSON_ID)
) ;

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER
(
CUSTOMER_ID NUMBER,
PERSON_ID NUMBER UNIQUE,
LOCATION_ID NUMBER NOT NULL,
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
CONSTRAINT CUSTOMER_FK1 FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
CONSTRAINT CUSTOMER_FK2 FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID) ON DELETE CASCADE
) ;

DROP TABLE DELIVERY_MAN;
CREATE TABLE DELIVERY_MAN
(
DELIVERY_MAN_ID NUMBER,
PERSON_ID NUMBER UNIQUE,
SALARY NUMBER NOT NULL,
IMAGE VARCHAR2(50) UNIQUE,
CONSTRAINT DELIVERY_MAN_PK PRIMARY KEY (DELIVERY_MAN_ID),
CONSTRAINT DELIVERY_MAN_FK FOREIGN KEY (DELIVERY_MAN_ID) REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE
) ;

DROP TABLE LOCATION;
CREATE TABLE LOCATION
(
LOCATION_ID NUMBER,
STREET_NO VARCHAR2(10),
CITY VARCHAR2(25) NOT NULL,
ZIP_CODE NUMBER NOT NULL,
CONSTRAINT LOCATION_PK PRIMARY KEY (LOCATION_ID)
) ;

DROP TABLE RESTAURANT
CREATE TABLE RESTAURANT
(
RESTAURANT_ID NUMBER,
NAME VARCHAR2(50) NOT NULL,
LOCATION_ID NUMBER NOT NULL,
PHONE_NO NUMBER NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
OPENING VARCHAR2(10),
CLOSING VARCHAR2(10),
CONSTRAINT RESTAURANT_PK PRIMARY KEY (RESTAURANT_ID),
CONSTRAINT RESTAURANT_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID) ON DELETE CASCADE
) ;

DROP TABLE FOOD;
CREATE TABLE FOOD
(
FOOD_ID NUMBER,
NAME VARCHAR2(50) NOT NULL,
CUISINE VARCHAR2(50) NOT NULL,
PRICE NUMBER NOT NULL,
AVAILABILTY VARCHAR2(50) NOT NULL,
CONSTRAINT FOOD_PK PRIMARY KEY (FOOD_ID)
) ;

DROP TABLE MENU;
CREATE TABLE MENU
(
RESTAURANT_ID NUMBER NOT NULL,
FOOD_ID NUMBER NOT NULL,
CONSTRAINT MENU_FK1 FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (RESTAURANT_ID) ON DELETE CASCADE,
CONSTRAINT MENU_FK2 FOREIGN KEY (FOOD_ID) REFERENCES FOOD (FOOD_ID) ON DELETE CASCADE
) ;

DROP TABLE PROMO;
CREATE TABLE PROMO
(
CODE VARCHAR2(50),
DISCOUNT_PCT NUMBER(10) NOT NULL,
START_TIME DATE NOT NULL,
END_TIME DATE NOT NULL,
STATUS VARCHAR2(10) NOT NULL,
CONSTRAINT PROMO_PK PRIMARY KEY (CODE)
) ;

DROP TABLE CUSTOMER_PROMO;
CREATE TABLE CUSTOMER_PROMO
(
CUSTOMER_ID NUMBER NOT NULL,
PROMO_CODE VARCHAR2(50) NOT NULL,
CONSTRAINT PERSON_PROMO_FK1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE,
CONSTRAINT PERSON_PROMO_FK2 FOREIGN KEY (PROMO_CODE) REFERENCES PROMO (CODE) ON DELETE CASCADE
) ;

DROP TABLE ORDERS;
CREATE TABLE ORDERS
(
ORDER_ID NUMBER,
ORDER_DATE DATE NOT NULL,
STAR_TIME DATE NOT NULL,
DELIVERY_TIME DATE NOT NULL,
CUSTOMER_ID NUMBER NOT NULL,
DELIVERY_MAN_ID NUMBER NOT NULL,
STATUS VARCHAR2(10) NOT NULL,
CONSTRAINT ORDERS_PK PRIMARY KEY (ORDER_ID),
CONSTRAINT ORDERS_FK1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE,
CONSTRAINT ORDERS_FK2 FOREIGN KEY (DELIVERY_MAN_ID) REFERENCES DELIVERY_MAN (DELIVERY_MAN_ID) ON DELETE CASCADE
) ;

DROP TABLE ORDERED_ITEMS;
CREATE TABLE ORDERED_ITEMS
(
ORDER_ID NUMBER NOT NULL,
FOOD_ID NUMBER NOT NULL,
CONSTRAINT ORDERED_ITEMS_FK1 FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE,
CONSTRAINT ORDERED_ITEMS_FK2 FOREIGN KEY (FOOD_ID) REFERENCES FOOD (FOOD_ID) ON DELETE CASCADE
) ;

DROP TABLE PAYMENTS;
CREATE TABLE PAYMENTS
(
PAYMENT_ID NUMBER,
AMOUNT NUMBER NOT NULL,
METHOD VARCHAR2(50),
PROMO_CODE VARCHAR2(50),
ORDER_ID NUMBER NOT NULL,
CONSTRAINT PAYMENT_PK PRIMARY KEY (PAYMENT_ID),
CONSTRAINT PAYMENTS_FK1 FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE,
CONSTRAINT PAYMENTS_FK2 FOREIGN KEY (PROMO_CODE) REFERENCES PROMO (CODE) ON DELETE CASCADE
) ;

DROP TABLE OFFERS;
CREATE TABLE OFFERS
(
OFFER_ID NUMBER,
FOOD_ID NUMBER NOT NULL,
DISCOUNT_PCT NUMBER NOT NULL,
MAX_DISCOUNT NUMBER NOT NULL,
EXPIRE_DATE DATE,
RESTAURANT_ID NUMBER NOT NULL,
CONSTRAINT OFFER_PK PRIMARY KEY (OFFER_ID),
CONSTRAINT OFFERS_FK1 FOREIGN KEY (FOOD_ID) REFERENCES FOOD (FOOD_ID) ON DELETE CASCADE,
CONSTRAINT OFFERS_FK2 FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (RESTAURANT_ID) ON DELETE CASCADE
) ;

DROP TABLE REVIEWS;
CREATE TABLE REVIEWS
(
REVIEW_ID NUMBER,
RATING NUMBER,
DESCRIPTION VARCHAR2(200),
FOOD_ID NUMBER NOT NULL,
CUSTOMER_ID NUMBER NOT NULL,
ORDER_ID NUMBER NOT NULL,
CONSTRAINT REVIEW_PK PRIMARY KEY (REVIEW_ID),
CONSTRAINT REVIEW_FK1 FOREIGN KEY (FOOD_ID) REFERENCES FOOD (FOOD_ID) ON DELETE CASCADE,
CONSTRAINT REVIEW_FK2 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE,
CONSTRAINT REVIEW_FK3 FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE
) ;




    CREATE TABLE PERSONS
    (
    PERSON_ID NUMBER,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    GENDER VARCHAR2(10) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL,
    PHONE NUMBER NOT NULL,
    BIRTH_DATE DATE,
    REGISTRATION_DATE DATE NOT NULL,
    CONSTRAINT PERSON_PK PRIMARY KEY (PERSON_ID),
    CONSTRAINT PASSWORD check (PASSWORD like '%[0-9]%' and PASSWORD like '%[A-Z]%' and PASSWORD like '%[!@#$%^&*()-_+=.,;:''"`~]%' and LENGTH(PASSWORD) >= 8)
    ) ;
